version: '3'

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
      - pip-volume:/app/vendor
    environment:
      PYTHONPATH: /app/vendor/bin
      PYTHONUSERBASE: /app/vendor
    ports:
      - 7000:7000
    command: 'uvicorn main:app --reload --host 0.0.0.0 --port 7000'
volumes:
  pip-volume:
